AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Parameter store template by Clouxter"

Resources:
  TopicArnReportVdcBackDashboardCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: "/config/vdc-back-dashboard-corresponsalia/aws.topic.arn.report"
      Value: "arn:aws:sns:us-east-1:870388276428:sns_t_reportes_corr_cert"
      Tier: Standard

  EndpointNameVdcBackReportCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: "/config/vdc-back-report-corresponsalia/cloud.aws.end-point.name"
      Value: "sqs_q_reportes_corr_cert"
      Tier: Standard

  DevelopmentPasswordDB:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: "/config/passwords/database.dev"
      Value: "R@!7I4pd&0%KS9iw"
      Tier: Standard
