AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Parameter store template by Clouxter"

Resources:
  TopicArnReportVdcBackDashboardCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Ref: parameterName1
      Value:
        Ref: parameterValue1
      Tier: Standard

  EndpointNameVdcBackReportCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Ref: parameterName2
      Value:
        Ref: parameterValue2
      Tier: Standard

  ExpirationTimeLimitVdcBackReportCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Ref: parameterName3
      Value:
        Ref: parameterValue3
      Tier: Standard
