AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Parameter store template by Clouxter from Git"

Parameters:
  TopicArnReportBackDasboardName:
    Type: String
  TopicArnReportBackDashboardValue:
    Type: String
  EndpointBackReportCorresponsaliaName:
    Type: String
  EndpointBackReportCorresponsaliaValue:
    Type: String
  PasswordDatabaseParameterName:
    Type: String
  PasswordDatabaseParameterValue:
    Type: String
    NoEcho: true
  UserNameDatabaseParameterName:
    Type: String
  UserNameDatabaseParameterValue:
    Type: String

Resources:
  TopicArnReportVdcBackDashboardCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref TopicArnReportBackDasboardName
      Value: !Ref TopicArnReportBackDashboardValue
      Tier: Standard

  EndpointNameVdcBackReportCorresponsalia:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref EndpointBackReportCorresponsaliaName
      Value: !Ref EndpointBackReportCorresponsaliaValue
      Tier: Standard

  PasswordDatabase:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref PasswordDatabaseParameterName
      Value: !Ref PasswordDatabaseParameterValue
      Tier: Standard

  UserNameDatabase:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref UserNameDatabaseParameterName
      Value: !Ref UserNameDatabaseParameterValue
      Tier: Standard